### ISSUE TITLE
Saijruulalah sanaa

### ISSUE THREAD

**Issue by myagmarsurensedjav** [dboldbaatar/GoogleWebFont#2]
Sain baina uu? 

Dajgui script baina.

Saijruulaad shuud url damjuulanguut dotorh font file uudiig ni tataad fonts havtast hiichdeg baival zugeer yum bish uu.

url: http://fonts.googleapis.com/css?family=Noto+Serif:400,700,400italic,700italic|Josefin+Sans:100,300,400,100italic|Asap|Ubuntu+Condensed|Hind|Play|Archivo+Narrow:400,400italic,700,700italic|Cuprum:400,700,700italic,400italic

tegeed css uudiig ni fonts.css geed

/fonts
--- font1.woff2
--- font2.woff2
/css
--- fonts.css

tegeed google ch geltgui duriin urlaas yalgaad avchdag bol bur amar.

**Comment by dboldbaatar** [comment]
иймэрхүү байдалтай ашиглаж үзсэн гэвч шууд file_get_contents('url') гэж ашиглахаар зөвхөн "latin" хэсэг нь л гарж ирсэн тэгээд ч ажлын дундуур хийж буй болохоор цаг тусд нь салгаж чадсангүй дээ.

**Comment by dboldbaatar** [comment]
ямартай ч баярлалаа.

**Comment by dboldbaatar** [comment]
Бага зэрэг засвар хийж хэрэглэхэд илүү хялбар болгосон байгаа шүү.
